pipeline {
    agent any

    stages {
        stage("Build") {
            steps {
                dir("my-app") {
                    sh "mvn clean package"
                }
            }
        }

        stage("SonarQube Analysis") {
            steps {
                dir("my-app") {
                    sh "sonar-scanner"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed. Check logs for details."
        }
    }
}
